Apply Button on Benefit info page
DTS-STN/ServicePrototypeFrontend pull request #13
Opened 2021-01-19 13:50 UTC by nghe0001

# Description 📝

Apply Button on Benefit info page

## Taiga Link 🔗

https://taiga.dts-stn.com/project/ericdube-hfp-shared-backlog/task/263?kanban-status=131

## Checklist ✅
- [ ] created story for all visual components
- [ ] created or modified necessary unit tests
- [ ] created or modified e2e tests
- [ ] modified README or any applicable documentation on the changes you made

2021-01-19 14:18 UTC, will0684 approved these changes
Thanks Kevin

2021-01-19 14:19 UTC, will0684 commented on src/components/organisms/BenefitGrid.stories.js
> +  benefitMoreInfoButtonText: "More Informationaaa",
This looks like a typo

2021-01-19 14:20 UTC, will0684 requested changes
Once the typo is fixed should be good to merge

2021-01-20 13:39 UTC, nghe0001 commented on src/components/organisms/BenefitGrid.stories.js
> +  benefitMoreInfoButtonText: "More Informationaaa",
corrected ty

2021-01-20 14:11 UTC, will0684 approved these changes
Nice thanks Kevin

2021-01-20 14:59 UTC, closed without merging