Task502 estimate benefit button
DTS-STN/ServicePrototypeFrontend pull request #78
Opened 2021-02-15 21:59 UTC by EphraimAssi

# Description 📝
Added a button for estimating benefits on benefit details page. 

## Taiga Link 🔗
https://taiga.dts-stn.com/project/ericdube-hfp-shared-backlog/task/502?kanban-status=134

## Checklist ✅
- [ ] created story for all visual components
- [ ] created or modified necessary unit tests
- [ ] created or modified e2e tests
- [ ] modified README or any applicable documentation on the changes you made

2021-02-16 13:46 UTC, will0684 commented on src/pages/benefit.js
> +        benefitData.benefitTag.includes("Internal") & keycloak.authenticated
The operator here should be "&&"

2021-02-16 13:47 UTC, will0684 requested changes
![image](https://user-images.githubusercontent.com/31868510/108071218-798f2780-7033-11eb-8167-e50a5f4ec3be.png)

This error appears when you go to a provincial benefit page.

2021-02-16 13:55 UTC, shewood reviewed
Would it be possible to make the button the same size as the Apply button?
Apart from that, it looks great so far.

2021-02-16 23:46 UTC, EphraimAssi commented
Fixed the code but couldn't adjust the button size since it varies in English and French.

2021-02-17 14:14 UTC, shewood approved these changes
Error is still there.

2021-02-17 14:16 UTC, shewood reviewed
Oh, I do still see the error. No estimates on the provincial pages.

2021-02-17 19:57 UTC, closed without merging